theme: jekyll-theme-slate
url: "https://sykefi.github.io/ry-tietomallit" # the base hostname & protocol for your site
home: "https://sykefi.github.io/ry-tietomallit/"
repository: sykefi/ry-tietomallit
title: "Rakennetun ympäristön tietomallit"
name: "Rakennetun ympäristön tietomallit"
name_short: "Rakennetun ympäristön tietomallit"
beta: true
#google_analytics: G-TL17CQFMFK
accessibility_statement_url: "/accessibility_statement.html"
plugins:
- jekyll-sitemap
- kramdown


